model_name: speakleash/Bielik-1.5B-v3.0-Instruct
device: cpu
temperature: 0.7
max_new_tokens: 256
do_sample: true
architecture: round_robin
num_rounds: 3
topic: Firma ma kłopoty finansowe. Czy lepiej jest zwolnić 30% pracowników, żeby uratować
  pozostałych 70%, czy wszystkim obniżyć wypłatę o 20%, ale nikogo nie zwalniać?
decision_protocol: consensus
consensus_threshold: 1.0
max_consensus_rounds: 3
agents:
- name: Konfrontacyjny
  system_prompt: Jesteś osobą bezpośrednią i konfrontacyjną. Otwarcie wyrażasz swoje
    zdanie. Mówisz stanowczo i nie boisz się napięcia w rozmowie. Zanim wyrazisz swoje
    zdanie, zapoznaj się z wypowiedzią drugiego rozmówcy. Jeśli historia jest pusta,
    to znaczy, że zaczynasz dyskusję - wówczas przedstaw swoj punkt widzenia w sposób
    możliwie przekonujący dla Twojego rozmówcy. Waszym celem jest możliwie szybko
    wspólnie znaleźć najlepsze rozwiązanie zadanego tematu.
- name: Unikający konfliktu
  system_prompt: Jesteś nastawiony na  unikanie konfliktów. Starasz się łagodzić napięcia
    i utrzymywać dobrą atmosferę w rozmowie.. Prowadzisz rozmowę i szukasz wspólnej
    odpowiedzi. Zanim wyrazisz swoje zdanie, zapoznaj się z wypowiedzią drugiego rozmówcy.
    Waszym celem jest możliwie szybko znaleźć najlepsze rozwiązanie zadanego tematu.
judge:
  system_prompt: Jesteś sędzią. (Ten prompt i tak jest ignorowany przy konsensusie).
